/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FirstComponent {
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyEmbededComponent {
        "color": string;
    }
    interface MyParentComponent {
    }
}
declare global {
    interface HTMLFirstComponentElement extends Components.FirstComponent, HTMLStencilElement {
    }
    var HTMLFirstComponentElement: {
        prototype: HTMLFirstComponentElement;
        new (): HTMLFirstComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyEmbededComponentElement extends Components.MyEmbededComponent, HTMLStencilElement {
    }
    var HTMLMyEmbededComponentElement: {
        prototype: HTMLMyEmbededComponentElement;
        new (): HTMLMyEmbededComponentElement;
    };
    interface HTMLMyParentComponentElement extends Components.MyParentComponent, HTMLStencilElement {
    }
    var HTMLMyParentComponentElement: {
        prototype: HTMLMyParentComponentElement;
        new (): HTMLMyParentComponentElement;
    };
    interface HTMLElementTagNameMap {
        "first-component": HTMLFirstComponentElement;
        "my-component": HTMLMyComponentElement;
        "my-embeded-component": HTMLMyEmbededComponentElement;
        "my-parent-component": HTMLMyParentComponentElement;
    }
}
declare namespace LocalJSX {
    interface FirstComponent {
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyEmbededComponent {
        "color"?: string;
    }
    interface MyParentComponent {
    }
    interface IntrinsicElements {
        "first-component": FirstComponent;
        "my-component": MyComponent;
        "my-embeded-component": MyEmbededComponent;
        "my-parent-component": MyParentComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "first-component": LocalJSX.FirstComponent & JSXBase.HTMLAttributes<HTMLFirstComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-embeded-component": LocalJSX.MyEmbededComponent & JSXBase.HTMLAttributes<HTMLMyEmbededComponentElement>;
            "my-parent-component": LocalJSX.MyParentComponent & JSXBase.HTMLAttributes<HTMLMyParentComponentElement>;
        }
    }
}
